# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160923_1640'),
        ('products', '0002_remove_product_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authors',
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(to='blog.Author'),
        ),
    ]
