# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160923_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='/static/media'),
        ),
    ]
