# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160924_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_url',
            field=models.URLField(null=True),
        ),
    ]
