# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
