# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20161010_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
